if (!window.torch) {
    window.torch = {};
}

window.torch.testData = [
    {"supplier": "DC Dental", "sku": "999-AN401", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "DC Dental", "sku": "650-2101052", "description": "Orabloc Cart 4% w/EPI 1:200k 50/Bx"},
    {"supplier": "DC Dental", "sku": "559-401072", "description": "Monoject Needles Metal 100/Bx 30S"},
    {"supplier": "DC Dental", "sku": "516-56846", "description": "RelyX Unicem 2 Automix Refill A2 U"},
    {"supplier": "DC Dental", "sku": "589-PIC", "description": "Pic-n-Stic 60/Bx"},
    {"supplier": "DC Dental", "sku": "516-41256", "description": "Scotchbond Universal L-Pop 100/Pk"},
    {"supplier": "DC Dental", "sku": "500-CPTYS-A2", "description": "Reflectys Caps .25gm 20/Pk A2"},
    {"supplier": "DC Dental", "sku": "500-FWTYS-A3.5", "description": "Reflectys Flow Syringe 2gm A3.5"},
    {"supplier": "DC Dental", "sku": "526-35053", "description": "Bib-Eze Disposable Bib Holder 250/Pk"},
    {"supplier": "DC Dental", "sku": "661-917343", "description": "Contour Neck Bib 17x18 2 Ply Blue 500/Cs"},
    {"supplier": "DC Dental", "sku": "661-912044", "description": "Venture Sponge NW 4x4 2000/Cs"},
    {"supplier": "DC Dental", "sku": "257-1500", "description": "Kleenex C-Fold Towels #150 2400/Cs"},
    {"supplier": "DC Dental", "sku": "257-21270", "description": "Tissue Kleenex Boutique 2-Ply White 95/Bx 36Bx/Cs"},
    {"supplier": "DC Dental", "sku": "694-77200", "description": "Seal-Tight Disposable Syringe Tips 200/Bg"},
    {"supplier": "DC Dental", "sku": "141-ZCWCP", "description": "Comfort Plus Saliva Ejector Clear w/White 100/bg"},
    {"supplier": "DC Dental", "sku": "999-EV405", "description": "Flexform Salive Ejectors 100/Bg"},
    {"supplier": "DC Dental", "sku": "995-SO9100", "description": "SRG Evacuation System Cleaner Gallon"},
    {"supplier": "DC Dental", "sku": "605-50Z362", "description": "Crystal HD Mirror Soft Grip #5 4/Pk"},
    {"supplier": "DC Dental", "sku": "516-71529", "description": "Imprint 4 Bite 50ml 2/Pk"},
    {"supplier": "DC Dental", "sku": "677-137016", "description": "Examix NDS Cartridge **No Tips** Regular 2/Bx"},
    {"supplier": "DC Dental", "sku": "677-138301", "description": "Exaflex Putty Standard Pk"},
    {"supplier": "DC Dental", "sku": "999-IM71512", "description": "Dynamic Mixing Tips Red (Penta) 50/Pk"},
    {"supplier": "DC Dental", "sku": "516-71461N", "description": "Garant Intraoral Tips White 50/Pk"},
    {"supplier": "DC Dental", "sku": "146-13451", "description": "Tra-Tens #1 Small Upper Perforated 12/Bx"},
    {"supplier": "DC Dental", "sku": "455-3227", "description": "Contour Plus PF Nitrile Glove Medium 100/Bx"},
    {"supplier": "DC Dental", "sku": "999-IC944", "description": "CSR Wrap 20\" x 20\" 500/Pk"},
    {"supplier": "DC Dental", "sku": "141-GCFCXSSF", "description": "SecureFit Ultra Sensitive White 50/Bx"},
    {"supplier": "DC Dental", "sku": "814-13-1000", "description": "Cavicide Gal/Bt"},
    {"supplier": "DC Dental", "sku": "616-IMS-1267", "description": "IMS Monitor Tape Green 60yd"},
    {"supplier": "DC Dental", "sku": "592-350110", "description": "HO Bands #1 Regular .001 100/Pk"},
    {"supplier": "DC Dental", "sku": "424-9007406", "description": "Glitter Prophy Paste Extra Coarse Mint 200/Bx"},
    {"supplier": "DC Dental", "sku": "592-138920", "description": "Classic Elite Flex DPA 200/Pk"},
    {"supplier": "DC Dental", "sku": "666-84843401", "description": "Glide Floss Pro-Health Original Refill 200m 2/Bx"},
    {"supplier": "DC Dental", "sku": "999-PR500", "description": "Chlorhexidine Gluconate 0.12% Oral Rinse"},
    {"supplier": "DC Dental", "sku": "380-1011-RB32", "description": "Duraflor 5% Fluoride .4mL Raspberry 32/Bx"},
    {"supplier": "DC Dental", "sku": "516-12115", "description": "Clinpro 5000 Toothpaste Van-Mint 4oz."},
    {"supplier": "DC Dental", "sku": "424-9065081", "description": "Cotton College Plier"},
    {"supplier": "DC Dental", "sku": "999-XR906", "description": "Bitewing Arm"},
    {"supplier": "DC Dental", "sku": "999-XR907", "description": "Bitewing Ring Red"},
    {"supplier": "DC Dental", "sku": "999-XR909", "description": "Bitewing Bite Blocks Red H2 25/Pk"},
    {"supplier": "DC Dental", "sku": "999-AN401", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "DC Dental", "sku": "999-AN410", "description": "Mepivacaine HCL 3% 50/Can"},
    {"supplier": "DC Dental", "sku": "999-AN304", "description": "Topical Benzocaine Gel 1oz Strawberry"},
    {"supplier": "DC Dental", "sku": "999-AN100", "description": "Needles Plastic 100/Bx 27L"},
    {"supplier": "DC Dental", "sku": "999-AN102", "description": "Needles Plastic 100/Bx 30S"},
    {"supplier": "DC Dental", "sku": "999-CE830", "description": "IRM-like Filling Material Kit"},
    {"supplier": "DC Dental", "sku": "999-CE830", "description": "IRM-like Filling Material Kit"},
    {"supplier": "DC Dental", "sku": "504-66001854", "description": "Gluma Desensitizer Single Dose 0.075mL 40/Pk"},
    {"supplier": "DC Dental", "sku": "999-DI750", "description": "Bib 2+1 Ply 13x18 500/Bx Blue"},
    {"supplier": "DC Dental", "sku": "169-32-LAG", "description": "Dri-Angle w/Silver Large 320/Bx"},
    {"supplier": "DC Dental", "sku": "999-DI451", "description": "All Gauze Sponges 2x2 N/S 8-Ply 5000/Cs"},
    {"supplier": "DC Dental", "sku": "999-IC44600AST", "description": "Safe Tip EZ Type Air/Water Tips Metal Core Rainbow 1600/Pk"},
    {"supplier": "DC Dental", "sku": "999-EV401", "description": "Saliva Ejector 100/Pk Clear W/Blue"},
    {"supplier": "DC Dental", "sku": "999-EV300-CS", "description": "High-Volume Evacuator Tips 100/Pk Case Pack 10/Cs"},
    {"supplier": "DC Dental", "sku": "777-H09945", "description": "Flexi Dam Non Latex Violet 6X6 Med 30/Bx"},
    {"supplier": "DC Dental", "sku": "559-412012", "description": "Monoject 412 Syringe Curved Tip 12cc 50/Bx"},
    {"supplier": "DC Dental", "sku": "771-J464G", "description": "Suture Vicryl Violet P3 4/0 18'' 12/Bx"},
    {"supplier": "DC Dental", "sku": "768-62-202", "description": "HeliPlug Collagen Wound Dressing 10/Bx"},
    {"supplier": "DC Dental", "sku": "146-34577-0", "description": "Matrix Bands Tofflemire #1 .002 36/Pk"},
    {"supplier": "DC Dental", "sku": "999-SL557", "description": "Surgical Carbide Bur by Midwest: 557?L "},
    {"supplier": "DC Dental", "sku": "872-BK01", "description": "Articulating Paper Pre-Cut Strips Blue 300/pk"},
    {"supplier": "DC Dental", "sku": "516-31741", "description": "Impregum Penta Soft Heavy Body Refill Kit"},
    {"supplier": "DC Dental", "sku": "516-31746", "description": "Impregum Penta Soft LB Rfill"},
    {"supplier": "DC Dental", "sku": "516-31642", "description": "Impregum Penta Medium Body Standard Pk"},
    {"supplier": "DC Dental", "sku": "461-77655", "description": "Genie Putty Regular Set 600ml/Pk"},
    {"supplier": "DC Dental", "sku": "516-71453", "description": "Protemp Plus Blue Mixing Tips 50/Pk"},
    {"supplier": "DC Dental", "sku": "999-IM71512", "description": "Dynamic Mixing Tips Red (Penta) 50/Pk"},
    {"supplier": "DC Dental", "sku": "999-IM886", "description": "Bite Registration Trays 50/Bx Posterior"},
    {"supplier": "DC Dental", "sku": "677-344011", "description": "Coe-Soft Professional Pack"},
    {"supplier": "DC Dental", "sku": "516-56941", "description": "3M ESPE Retraction Capsule Refill 25/Pk"},
    {"supplier": "DC Dental", "sku": "424-9007071", "description": "Hemodent Liquid 10cc Bt"},
    {"supplier": "DC Dental", "sku": "999-IC905-CS", "description": "Self-Seal Sterilization Pouches 200/Bx 3.5\" x 6.5\" 10/CS"},
    {"supplier": "DC Dental", "sku": "999-IC930-CS", "description": "Self-Seal Sterilization Pouches 200/Bx 5.25\"x11\" (5.25\" x 10\")  10/CS"},
    {"supplier": "DC Dental", "sku": "999-IC944", "description": "CSR Wrap 20\" x 20\" 500/Pk"},
    {"supplier": "DC Dental", "sku": "999-IC741", "description": "Barrier Film 1200/Roll Clear"},
    {"supplier": "DC Dental", "sku": "141-GPLUSBL", "description": "Isofluid Plus Earloop Masks Blue 50/Bx"},
    {"supplier": "DC Dental", "sku": "814-13-5100", "description": "CaviWipes1 Large 6\"x6.75\" 160/Cn"},
    {"supplier": "DC Dental", "sku": "999-EV100", "description": "Evacuation System Cleaner 64oz"},
    {"supplier": "DC Dental", "sku": "999-IC210", "description": "Ultrasonic Cleaning Tabs 64/Bx"},
    {"supplier": "DC Dental", "sku": "999-IC752", "description": "Chair Sleeve Half 27.5\"X24\" 225/Bx"},
    {"supplier": "DC Dental", "sku": "616-IMS-1250", "description": "IMS Monitor Tape Blank 60yd"},
    {"supplier": "DC Dental", "sku": "424-9011101", "description": "Vac Attak Evacuation Cleaner 800gm/Jr"},
    {"supplier": "DC Dental", "sku": "666-84843402", "description": "Glide Floss Pro-Health Original Dispenser 200m"},
    {"supplier": "DC Dental", "sku": "609-TDPS", "description": "BridgeAid Dental Floss Threader 1000/Bx"},
    {"supplier": "DC Dental", "sku": "999-PR452", "description": "Dream Fluoride Varnish .40ml x 50/Pk Spearmint"},
    {"supplier": "DC Dental", "sku": "145-0244", "description": "Dura-White Stones FG FL2 12/Bx"},
    {"supplier": "DC Dental", "sku": "999-AN401", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "DC Dental", "sku": "999-CO133", "description": "Etching Gel 4x1.2ml Syringe +20 Tips"},
    {"supplier": "DC Dental", "sku": "394-AP100S", "description": "AloePRO PF Latex Glove S 100/Bx"},
    {"supplier": "DC Dental", "sku": "171-44026", "description": "Listerine UltraClean Unwaxed Teflon Floss 5 Yards Mint 72/Ca"},
    {"supplier": "DC Dental", "sku": "146-13455", "description": "Waterpik Tra-Ten Impression Tray Sz 5 Med Lower Perforated 12/Bx"},
    {"supplier": "DC Dental", "sku": "685-S457S", "description": "Blu-Mousse Split Cartridge Package 30 Second Set 2/Pk"},
    {"supplier": "DC Dental", "sku": "685-S284", "description": "Brush & Bond Self Etch Bonding Agent Light Cure Complete Kit Ea"},
    {"supplier": "DC Dental", "sku": "559-450004", "description": "Monoject Saliva Ejectors Blue 250/Bg"},
    {"supplier": "DC Dental", "sku": "333-elmp-b", "description": "Earloop Face Mask Blue 50/Bx "},
    {"supplier": "DC Dental", "sku": "761-AECM17-18XPX", "description": "Curette McCall Double End 17/18 XP EagleLite Resin"},
    {"supplier": "DC Dental", "sku": "761-AECC13-14XPX", "description": "Curette Columbia Double End 13/14 XP EagleLite Resin"},
    {"supplier": "DC Dental", "sku": "685-S371", "description": "Amalgambond Plus Catalyst .7ml"},
    {"supplier": "DC Dental", "sku": "747-6SR", "description": "Evacuation Cup Liners For Adec 6SR 250/Pk"},
    {"supplier": "DC Dental", "sku": "991-1430735", "description": "Carbocaine Plain Cartridges 3% 50/Bx"},
    {"supplier": "DC Dental", "sku": "333-TF7901", "description": "Sabur Trimming & Finishing Bur #7901 10/Pk"},
    {"supplier": "DC Dental", "sku": "212-0123C", "description": "Neo Diamonds FG 0123C Ball 25/PK"},
    {"supplier": "DC Dental", "sku": "685-S449", "description": "Snap Acrylic Powder 69/C2/D4 40gm/Bt"},
    {"supplier": "DC Dental", "sku": "999-CO180", "description": "Micro Brush Applicators 4x100/Pk Regular"},
    {"supplier": "DC Dental", "sku": "677-002592", "description": "Gradia Direct X 20 Unitip X-A3"},
    {"supplier": "DC Dental", "sku": "500-DCB-50", "description": "DentoCore Cartridge 50gm White"},
    {"supplier": "DC Dental", "sku": "999-MA200", "description": "Matrix Bands .001 Ultra Thin #1 12/Pk"},
    {"supplier": "DC Dental", "sku": "999-DI800", "description": "Tray Covers Ritter B 1000/Cs White"},
    {"supplier": "DC Dental", "sku": "999-DI758", "description": "Bib 2+1 Ply 13x18 500/Bx Silver Gray"},
    {"supplier": "DC Dental", "sku": "999-EV100", "description": "Evacuation System Cleaner 64oz"},
    {"supplier": "DC Dental", "sku": "912-370111", "description": "Benda Brush Mini 144/Bx"},
    {"supplier": "DC Dental", "sku": "559-412012", "description": "Monoject 412 Syringe Curved Tip 12cc 50/Bx"},
    {"supplier": "DC Dental", "sku": "526-27416", "description": "Image Dustless Pouches FS 1Lb"},
    {"supplier": "DC Dental", "sku": "995-VP9003", "description": "Defend VPS Material 4x50ml LB-RS"},
    {"supplier": "DC Dental", "sku": "999-IM512", "description": "HP Mixing Tips 48/Bag Teal 6.5mm"},
    {"supplier": "DC Dental", "sku": "146-13451", "description": "Tra-Tens #1 Small Upper Perforated 12/Bx"},
    {"supplier": "DC Dental", "sku": "999-IC920", "description": "Self-Seal Sterilization Pouches 200/Bx 3.5\"x10\""},
    {"supplier": "DC Dental", "sku": "999-IC798", "description": "Autoclave Cleaner Quart"},
    {"supplier": "DC Dental", "sku": "999-IC230", "description": "Tartar & Stain Remover Liquid Gallon"},
    {"supplier": "DC Dental", "sku": "999-DI651", "description": "HR Cover Poly 14\"X9.5\" 250/Bx"},
    {"supplier": "DC Dental", "sku": "999-IC531", "description": "Lab Jackets Ceil Blue Medium 10/Bag"},
    {"supplier": "DC Dental", "sku": "999-IC570", "description": "Lab Coat Ceil Blue Small 10/Bag"},
    {"supplier": "DC Dental", "sku": "999-PR809", "description": "Prophy Paste Cups 200/Bx Mint Coarse"},
    {"supplier": "DC Dental", "sku": "999-PR500", "description": "Chlorhexidine Gluconate 0.12% Oral Rinse"},
    {"supplier": "DC Dental", "sku": "999-MI410", "description": "Retainer Boxes 12/Pk Asst."},
    {"supplier": "DC Dental", "sku": "999-CO166", "description": "Pre-Bent Dispensing Tips 25ga Blue 100/bag"},
    {"supplier": "DC Dental", "sku": "999-DI650", "description": "HR Cover Poly 11\"X9.5\" 250/Bx"},
    {"supplier": "DC Dental", "sku": "999-AC140", "description": "Crown And Bridge 4:1 and 10:1 Mixing Tips Light Blue 50/bag"},
    {"supplier": "DC Dental", "sku": "999-IM520", "description": "Intraoral Mixing Tips Yellow 100/bag "},
    {"supplier": "DC Dental", "sku": "616-EXTU17/236", "description": "TU 17/23 Explorer Double End #6 Satin Steel Handle"},
    {"supplier": "DC Dental", "sku": "141-ZWW", "description": "Premium Saliva Ejectors White 100/bg"},
    {"supplier": "DC Dental", "sku": "999-IC111-CS", "description": "Gloves Latex PF Small 100/Bx Case Pack 10/Cs"},
    {"supplier": "DC Dental", "sku": "999-IM526", "description": "HP T-Style Mixing Tips 48/Bag Teal 6.5mm"},
    {"supplier": "DC Dental", "sku": "999-IM54_", "description": "VPS Impression Material - Light Body 50 ml 2/pk FS or RS"},
    {"supplier": "DC Dental", "sku": "328-A1400", "description": "Septocaine Cartridges 4% w/Epi 1:100,000 50/Bx"},
    {"supplier": "DC Dental", "sku": "409-0886-31", "description": "Hurricaine Topical Gel Pina Colada 1oz/Jr"},
    {"supplier": "DC Dental", "sku": "999-AN103", "description": "Needles Plastic 100/Bx 30XS"},
    {"supplier": "DC Dental", "sku": "516-56874", "description": "Relyx Unicem 2 Clicker Translucent 11Gm"},
    {"supplier": "DC Dental", "sku": "644-031457500", "description": "GeriStore Syringeable Starter Kit A2"},
    {"supplier": "DC Dental", "sku": "677-441002", "description": "FujiCEM 2 Automix Refill 2/Pk (SL Tips)"},
    {"supplier": "DC Dental", "sku": "999-CO133", "description": "Etching Gel 4x1.2ml Syringe +20 Tips"},
    {"supplier": "DC Dental", "sku": "317-213332", "description": "LuxaCore Z-Dual Automix Refill Kit Light Opaque"},
    {"supplier": "DC Dental", "sku": "813-33381", "description": "Optibond All-in-One Bottle"},
    {"supplier": "DC Dental", "sku": "516-6032A3", "description": "Filtek Supreme Ultra Flowable A3 Syringe Refill 2x2g"},
    {"supplier": "DC Dental", "sku": "399-1403", "description": "Jet Repair Acrylic Liquid 118Ml/Bt"},
    {"supplier": "DC Dental", "sku": "317-110907", "description": "Luxatemp Ultra Refill A2"},
    {"supplier": "DC Dental", "sku": "141-WEXBL", "description": "Econoback Bibs 13x19 500/Cs Blue"},
    {"supplier": "DC Dental", "sku": "999-DI311", "description": "Plastic Cups 5oz. 1000/Cs White"},
    {"supplier": "DC Dental", "sku": "999-IC122205", "description": "Sani-Tip Type Air/Water Tips Plastic Clear 1500/Pk"},
    {"supplier": "DC Dental", "sku": "999-EV400", "description": "Saliva Ejector 100/Pk White"},
    {"supplier": "DC Dental", "sku": "999-EV300", "description": "High-Volume Evacuator Tips 100/Pk"},
    {"supplier": "DC Dental", "sku": "768-67-664/5", "description": "Miltex Mirror Plane CS #5"},
    {"supplier": "DC Dental", "sku": "999-IM610", "description": "Curved 412 Utility Syringe 12cc 50/Pk"},
    {"supplier": "DC Dental", "sku": "526-27456", "description": "Identic Dust Free Canister Fast Set 1Lb"},
    {"supplier": "DC Dental", "sku": "999-IM301", "description": "Bite Registration Cartridge 2/Pk FS"},
    {"supplier": "DC Dental", "sku": "424-9007093", "description": "Traxodent Starter Pack 7/Pk"},
    {"supplier": "DC Dental", "sku": "999-IC920", "description": "Self-Seal Sterilization Pouches 200/Bx 3.5\"x10\""},
    {"supplier": "DC Dental", "sku": "999-IC740", "description": "Barrier Film 1200/Roll Blue"},
    {"supplier": "DC Dental", "sku": "814-13-1100", "description": "CaviWipes Towelettes Disinfect Large 160/Cn"},
    {"supplier": "DC Dental", "sku": "999-DI650", "description": "HR Cover Poly 11\"X9.5\" 250/Bx"},
    {"supplier": "DC Dental", "sku": "424-9007600", "description": "Enamel Pro Paste Mint Fine 200/Bx"},
    {"supplier": "DC Dental", "sku": "502-422B", "description": "Suture Polysyn Pga Undyed C-6 4-0 27\" 12/Bx"},
    {"supplier": "DC Dental", "sku": "768-62-202", "description": "HeliPlug Collagen Wound Dressing 10/Bx"},
    {"supplier": "DC Dental", "sku": "141-EEB", "description": "Edge Ease Blue 300/Bx"},
    {"supplier": "DC Dental", "sku": "999-XR710", "description": "Lead Apron Adult W/Collar Beige"},
    {"supplier": "DC Dental", "sku": "999-IC111", "description": "Gloves Latex PF Small 100/Bx"},
    {"supplier": "DC Dental", "sku": "972-P63884", "description": "Sani-Cloth AF3 Wipes X-Large 65/Pk"},
    {"supplier": "DC Dental", "sku": "999-IN04-923", "description": "House Brand Explorere SE 23"},
    {"supplier": "DC Dental", "sku": "559-85131", "description": "Sharps Container Mailbox Style 5 Qt"},
    {"supplier": "DC Dental", "sku": "666-80285847", "description": "Crest Pro-Health Advanced Extra Deep Clean 1 Liter 6/cs"},
    {"supplier": "DC Dental", "sku": "813-33035", "description": "Alginot Refill Cartridges 24/Pack"},
    {"supplier": "DC Dental", "sku": "999-IC240", "description": "Ultrasonic General Purpose Cleaner 1 Gal"},
    {"supplier": "DC Dental", "sku": "852-15-200", "description": "Banicide Plus cold Sterile 1 Gal"},
    {"supplier": "DC Dental", "sku": "999-EV500", "description": "green suction tips size 1/4 25/pk"},
    {"supplier": "DC Dental", "sku": "999-SU304", "description": "Blades SS Sterile Size 15 100/BX"},
    {"supplier": "DC Dental", "sku": "326-261001", "description": "Expasyl Paste Retraction System Refill Strawberry 20/Pk"},
    {"supplier": "DC Dental", "sku": "328-A1400", "description": "Septocaine - Septodont"},
    {"supplier": "DC Dental", "sku": "999-AN401", "description": "Lidocaine 2% Red"},
    {"supplier": "DC Dental", "sku": "999-AN302", "description": "Benzo-Jel Topical Anesthetic Gel Mint 1oz/Jr"},
    {"supplier": "DC Dental", "sku": "999-AN304", "description": "Benzo-Jel Topical Anesthetic Gel Strawberry 1oz/Jr"},
    {"supplier": "DC Dental", "sku": "804-L8002", "description": "sodium cloride inj bag 0.90% 250ml"},
    {"supplier": "DC Dental", "sku": "999-EV300", "description": "High Volume Evac Tips 100-Bag"},
    {"supplier": "DC Dental", "sku": "504-66039008", "description": "Venus Diamond Composite PLT Universal A1 0.25 Gm Refill 20/Bx"},
    {"supplier": "DC Dental", "sku": "504-66039009", "description": "Venus Diamond Composite PLT Universal A2 0.25 Gm Refill 20/Bx"},
    {"supplier": "DC Dental", "sku": "135-14072-5", "description": "Carbide Bur Surgical Friction Grip Surgical Length 702 5/Pk"},
    {"supplier": "DC Dental", "sku": "999-IC910", "description": "Sterila Pouches 2.75\" x 10\" 200/bx "},
    {"supplier": "DC Dental", "sku": "999-DI801", "description": "Tray covers 8.5\" x 12.25\" 1000/ca Blue"},
    {"supplier": "DC Dental", "sku": "328-A1400", "description": "Septocaine - Septodont"},
    {"supplier": "DC Dental", "sku": "516-1982C", "description": "Sof-Lex Pop On Disc 0.5 in Coarse Refill Black Right Angle 85/Bx"},
    {"supplier": "DC Dental", "sku": "686-17S", "description": "Clear Safety Glasses"},
    {"supplier": "DC Dental", "sku": "589-ET-50R", "description": "Etch-Rite Etching Gel Thixotropic 2x25 mL Jumbo Syringe Refill 2/pack"},
    {"supplier": "DC Dental", "sku": "872-BK01", "description": "Articulating Paper Blue Plastic Dispenser 300/Bx"},
    {"supplier": "DC Dental", "sku": "516-44313", "description": "Cavit-G Temporary Filling Material 28 Gm Jar Grey Ea"},
    {"supplier": "DC Dental", "sku": "424-9007131", "description": "RC Prep Cleanser Urea Peroxide and EDTA Jar Ea"},
    {"supplier": "DC Dental", "sku": "198-80010", "description": "Caries Finder Dye Red 10ml"},
    {"supplier": "DC Dental", "sku": "693-2893KA", "description": "Clearfil S3 Bond Plus Slf Etch Bonding Agent LC Val Pkg 3/Pk"},
    {"supplier": "DC Dental", "sku": "999-CO131", "description": "Etching Gel 12gm Syrine + 20 Tips"},
    {"supplier": "DC Dental", "sku": "516-41256", "description": "Scotchbond Universal L-Pop 100/Pk"},
    {"supplier": "DC Dental", "sku": "999-MA350", "description": "Toff Dead Sft Mtrx Bnd SS 1 Ultr Thn .001\" 12/Pk"},
    {"supplier": "DC Dental", "sku": "768-67-664/5", "description": "Miltex Mirror Plane CS #5 (12 pack)"},
    {"supplier": "DC Dental", "sku": "999-DI750", "description": "Bib 2+1 Ply 13x18 500/Bx Blue"},
    {"supplier": "DC Dental", "sku": "852-05-305", "description": "Occlude Aerosol Powder Green 75gm/Cn"},
    {"supplier": "DC Dental", "sku": "999-AN307", "description": "Topical Benzocaine Gel 1oz Grape"},
    {"supplier": "DC Dental", "sku": "999-AN102", "description": "Needles Plastic 100/Bx 30S"},
    {"supplier": "DC Dental", "sku": "999-AN100", "description": "Needles Plastic 100/Bx 27L"},
    {"supplier": "DC Dental", "sku": "999-AN100", "description": "Needles Plastic 100/Bx 27L"},
    {"supplier": "Henry Schein", "sku": "465-1205", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "Henry Schein", "sku": "465-1205", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "Henry Schein", "sku": "101-1993", "description": "Topical Benzocaine Gel 1oz Strawberry"},
    {"supplier": "Henry Schein", "sku": "384-6709", "description": "Articulating Paper Pre-Cut Strips Blue 300/pk"},
    {"supplier": "Henry Schein", "sku": "465-1205", "description": "Lidocaine HCL 2% W/EPI 1:100,000 50/Can"},
    {"supplier": "Henry Schein", "sku": "100-4649", "description": "Etching Gel 4x1.2ml Syringe +20 Tips"},
    {"supplier": "Henry Schein", "sku": "108-7850", "description": "AloePRO PF Latex Glove S 100/Bx"},
    {"supplier": "Henry Schein", "sku": "555-0789", "description": "Listerine UltraClean Unwaxed Teflon Floss 5 Yards Mint 72/Ca"},
    {"supplier": "Henry Schein", "sku": "112-9062", "description": "Waterpik Tra-Ten Impression Tray Sz 5 Med Lower Perforated 12/Bx"},
    {"supplier": "Henry Schein", "sku": "186-2170", "description": "Blu-Mousse Split Cartridge Package 30 Second Set 2/Pk"},
    {"supplier": "Henry Schein", "sku": "186-5811", "description": "Brush & Bond Self Etch Bonding Agent Light Cure Complete Kit Ea"},
    {"supplier": "Henry Schein", "sku": "194-4601", "description": "Monoject Saliva Ejectors Blue 250/Bg"},
    {"supplier": "Henry Schein", "sku": "104-3809", "description": "Earloop Face Mask Blue 50/Bx "},
    {"supplier": "Henry Schein", "sku": "822-5702", "description": "Curette McCall Double End 17/18 XP EagleLite Resin"},
    {"supplier": "Henry Schein", "sku": "822-8544", "description": "Curette Columbia Double End 13/14 XP EagleLite Resin"},
    {"supplier": "Henry Schein", "sku": "186-1119", "description": "Amalgambond Plus Catalyst .7ml"},
    {"supplier": "Henry Schein", "sku": "100-9195", "description": "Evacuation Cup Liners For Adec 6SR 250/Pk"},
    {"supplier": "Henry Schein", "sku": "228-8210", "description": "Septocaine Cartridges 4% w/Epi 1:100,000 50/Bx"},
    {"supplier": "Henry Schein", "sku": "100-4649", "description": "Etching Gel 4x1.2ml Syringe +20 Tips"},
    {"supplier": "Henry Schein", "sku": "101-4856", "description": "High-Volume Evacuator Tips 100/Pk"},
    {"supplier": "Henry Schein", "sku": "1005725", "description": "Lead Apron Adult W/Collar Beige"},
    {"supplier": "Henry Schein", "sku": "B2610", "description": "Gloves Latex PF Small 100/Bx"},
    {"supplier": "Henry Schein", "sku": "10815134-6", "description": "Sani-Cloth AF3 Wipes X-Large 65/Pk"},
    {"supplier": "Henry Schein", "sku": "107-7265", "description": "House Brand Explorere SE 23"},
    {"supplier": "Henry Schein", "sku": "890-7866" , "description": "Sharps Container Mailbox Style 5 Qt"},
    {"supplier": "Henry Schein", "sku": "123-5066", "description": "Alginot Refill Cartridges 24/Pack"},
    {"supplier": "Henry Schein", "sku": "100-3836", "description": "Ultrasonic General Purpose Cleaner 1 Gal"},
    {"supplier": "Henry Schein", "sku": "115-4814", "description": "Banicide Plus cold Sterile 1 Gal"},
    {"supplier": "Henry Schein", "sku": "102-9023", "description": "green suction tips size 1/4 25/pk"},
    {"supplier": "Henry Schein", "sku": "112-6178", "description": "Blades SS Sterile Size 15 100/BX"},
    {"supplier": "Henry Schein", "sku": "621-0130", "description": "Expasyl Paste Retraction System Refill Strawberry 20/Pk"},
    {"supplier": "Henry Schein", "sku": "228-8210", "description": "Septocaine - Septodont"},
    {"supplier": "Henry Schein", "sku": "465-1205", "description": "Lidocaine 2% Red"},
    {"supplier": "Henry Schein", "sku": "570-0363", "description": "Benzo-Jel Topical Anesthetic Gel Mint 1oz/Jr"},
    {"supplier": "Henry Schein", "sku": "101-1993", "description": "Benzo-Jel Topical Anesthetic Gel Strawberry 1oz/Jr"},
    {"supplier": "Henry Schein", "sku": "118-0925", "description": "sodium cloride inj bag 0.90% 250ml"},
    {"supplier": "Henry Schein", "sku": "101-4856", "description": "High Volume Evac Tips 100-Bag"},
    {"supplier": "Henry Schein", "sku": "665-5041", "description": "Venus Diamond Composite PLT Universal A1 0.25 Gm Refill 20/Bx"},
    {"supplier": "Henry Schein", "sku": "665-0364", "description": "Venus Diamond Composite PLT Universal A2 0.25 Gm Refill 20/Bx"},
    {"supplier": "Henry Schein", "sku": "999-5929", "description": "Carbide Bur Surgical Friction Grip Surgical Length 702 5/Pk"},
    {"supplier": "Henry Schein", "sku": "Sp2-2710", "description": "Sterila Pouches 2.75\" x 10\" 200/bx "},
    {"supplier": "Henry Schein", "sku": "228-8210", "description": "Septocaine - Septodont"},
    {"supplier": "Henry Schein", "sku": "777-3240", "description": "Sof-Lex Pop On Disc 0.5 in Coarse Refill Black Right Angle 85/Bx"},
    {"supplier": "Henry Schein", "sku": "10315129", "description": "Clear Safety Glasses"},
    {"supplier": "Henry Schein", "sku": "384-4479", "description": "Etch-Rite Etching Gel Thixotropic 2x25 mL Jumbo Syringe Refill 2/pack"},
    {"supplier": "Henry Schein", "sku": "384-6709", "description": "Articulating Paper Blue Plastic Dispenser 300/Bx"},
    {"supplier": "Henry Schein", "sku": "378-8695", "description": "Cavit-G Temporary Filling Material 28 Gm Jar Grey Ea"},
    {"supplier": "Henry Schein", "sku": "378-4499", "description": "RC Prep Cleanser Urea Peroxide and EDTA Jar Ea"},
    {"supplier": "Henry Schein", "sku": "102-8155", "description": "Caries Finder Dye Red 10ml"},
    {"supplier": "Henry Schein", "sku": "721-0379", "description": "Clearfil S3 Bond Plus Slf Etch Bonding Agent LC Val Pkg 3/Pk"},
    {"supplier": "DHPI", "sku": "120-A1400", "description": "Septocaine Cartridges 4% w/Epi 1:100,000 50/Bx"},
    {"supplier": "DHPI", "sku": "120-088631", "description": "Hurricaine Topical Gel Pina Colada 1oz/Jr"},
    {"supplier": "DHPI", "sku": "130-DN3100", "description": "Needles Plastic 100/Bx 30XS"},
    {"supplier": "DHPI", "sku": "223-56874", "description": "Relyx Unicem 2 Clicker Translucent 11Gm"},
    {"supplier": "DHPI", "sku": "200-031476100", "description": "GeriStore Syringeable Starter Kit A2"},
    {"supplier": "DHPI", "sku": "220-10003", "description": "Etching Gel 4x1.2ml Syringe +20 Tips"},
    {"supplier": "DHPI", "sku": "380-213332", "description": "LuxaCore Z-Dual Automix Refill Kit Light Opaque"},
    {"supplier": "DHPI", "sku": "110-1403", "description": "Jet Repair Acrylic Liquid 118Ml/Bt"},
    {"supplier": "DHPI", "sku": "110-110907", "description": "Luxatemp Ultra Refill A2"},
    {"supplier": "DHPI", "sku": "640-WEXBL", "description": "Econoback Bibs 13x19 500/Cs Blue"},
    {"supplier": "DHPI", "sku": "630-HT01B2", "description": "Plastic Cups 5oz. 1000/Cs White"},
    {"supplier": "DHPI", "sku": "540-122205", "description": "Sani-Tip Type Air/Water Tips Plastic Clear 1500/Pk"},
    {"supplier": "DHPI", "sku": "540-HT100WW2", "description": "Saliva Ejector 100/Pk White"},
    {"supplier": "DHPI", "sku": "540-HT30100", "description": "High-Volume Evacuator Tips 100/Pk"},
    {"supplier": "DHPI", "sku": "701-676645", "description": "Miltex Mirror Plane CS #5"},
    {"supplier": "DHPI", "sku": "130-10001", "description": "Curved 412 Utility Syringe 12cc 50/Pk"},
    {"supplier": "DHPI", "sku": "298-608522", "description": "Identic Dust Free Canister Fast Set 1Lb"},
    {"supplier": "DHPI", "sku": "150-102", "description": "Bite Registration Cartridge 2/Pk FS"},
    {"supplier": "DHPI", "sku": "327-9007093", "description": "Traxodent Starter Pack 7/Pk"},
    {"supplier": "DHPI", "sku": "600-10006", "description": "Self-Seal Sterilization Pouches 200/Bx 3.5\"x10\""},
    {"supplier": "DHPI", "sku": "660-HT46B", "description": "Barrier Film 1200/Roll Blue"},
    {"supplier": "DHPI", "sku": "510-131100", "description": "CaviWipes Towelettes Disinfect Large 160/Cn"},
    {"supplier": "DHPI", "sku": "620-L0CP", "description": "HR Cover Poly 11\"X9.5\" 250/Bx"},
    {"supplier": "DHPI", "sku": "997-9007600", "description": "Enamel Pro Paste Mint Fine 200/Bx"},
    {"supplier": "DHPI", "sku": "850-422B", "description": "Suture Polysyn Pga Undyed C-6 4-0 27\" 12/Bx"},
    {"supplier": "DHPI", "sku": "860-62202", "description": "HeliPlug Collagen Wound Dressing 10/Bx"},
    {"supplier": "DHPI", "sku": "930-eeb", "description": "Edge Ease Blue 300/Bx"}
];

// automatically assign unique IDs, set quantity to 0 and addedToCart to false
for (var i = 0; i < window.torch.testData.length; i++) {
    window.torch.testData[i].id = i;
    window.torch.testData[i].quantity = 0;
    window.torch.testData[i].addedToCart = false;
}
